runtime: python37

includes:
  - credentials.yaml

handlers :
- url: /service-worker.js
  static_files: static/js/service-worker.js
  upload: static/js/service-worker.js
  mime_type: application/javascript
- url: /manifest.json
  static_files: static/manifest.json
  upload: static/manifest.json
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
- url: /static
  static_dir: static
- url: /.*
  script: auto
