runtime: python37

handlers :
- url: /service-worker.js
  static_files: static/js/service-worker.js
  upload: static/js/service-worker.js
  mime_type: application/javascript
- url: /manifest.json
  static_files: static/manifest.json
  upload: static/manifest.json
- url: /static
  static_dir: /static
- url: /.*
  script: auto
