runtime: python37

handlers : 
-  url: /sitemaps.xml
   static_files : static/sitemaps.xml
   upload : static/sitemaps.xml
-  url: /manifest.json
   static_files : static/manifest.json
   upload : static/manifest.json
-  url: /favicon.ico
   static_files : static/images/favicon.png
   upload : static/images/favicon.png
-  url: /icon-192.png
   static_files : static/images/icon-192.png
   upload : static/images/icon-192.png   
-  url: /service-worker.js
   static_files : static/js/service-worker.js
   upload : static/js/service-worker.js
   mime_type : application/javascript
-  url: /static
   static_dir: static
-  url: /fonts
   static_dir: fonts
-  url: /
   script : index.app
   login : optional
-  url: /admin/.*
   script: utilitair.app
   login: optional
-  url: /.*
   script: index.app
   login : optional